### ISSUE TITLE
Update URL upon click

### ISSUE THREAD

**Issue by srikanthBezawada** [koii-network/home#197]
- https://koii.network/learn/news/  has "see-all" which seems to point to wrong URL.
<img width="703" alt="Screenshot 2021-07-23 at 12 32 52 AM" src="https://user-images.githubusercontent.com/7630967/126694919-eedeff58-d49b-45e8-9f19-abcddafa0756.png">

- "Apply for partnerships" and "Apply for grants" seem to point to the same form.

<img width="246" alt="Screenshot 2021-07-23 at 12 34 41 AM 1" src="https://user-images.githubusercontent.com/7630967/126695173-46d8a68c-20ae-47b2-8de4-6a66dd60003a.png">

**Comment by somali0128** [comment]
- for the first one, it's not a URL issue, more like a DNS issue. Not sure why this happen so I hide it for now. (it jump to _blog.koii.network_ before, users can still reach this page by clicking the _see all_ button near the _Koii in the News_)
- These two jump to the same form. I seperate these cause in this way the footer will look more neat
